### ISSUE TITLE
can't recover from a read timeout

### ISSUE THREAD

**Issue by twinther** [breunigs/duplicity-acdcli#12]
See example below.
A file transfer failed due to a read time out.
Duplicity retries the upload, but this fails because the cache is outdated.
Perhaps a sync could be automatically performed in the case when acdcli return the 256 error code which means cache outdated?
I think duplicity would be able to recover and continue the transfer on third retry in this case.

```
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: none
Last full backup is too old, forcing full backup
Attempt 1 failed. BackendException: Error running 'acd_cli upload --force --overwrite '/tmp/duplicity-01ebyH-tempdir/duplicity-full.20160927T164650Z.vol11.difftar.gpg' 
'/duplicity/files'': returned 8, with output:
[                         ]   0.0% of  100MiB  0/1  -35.0MB/s       0s
1 file(s) failed.

16-09-27 19:16:19.235 [ERROR] [acd_cli] - Uploading "duplicity-full.20160927T164650Z.vol11.difftar.gpg" failed. RequestError: 1000, HTTPSConnectionPool(host='content-na
.drive.amazonaws.com', port=443): Read timed out. (read timeout=60).

Attempt 2 failed. BackendException: Error running 'acd_cli upload --force --overwrite '/tmp/duplicity-01ebyH-tempdir/duplicity-full.20160927T164650Z.vol11.difftar.gpg' 
'/duplicity/files'': returned 1, with output:
[#########################] 100.0% of  100MiB  1/1   87.8KB/s       0s
1 file(s) failed.

16-09-27 19:19:05.877 [ERROR] [acd_cli] - Uploading "duplicity-full.20160927T164650Z.vol11.difftar.gpg" failed. Name collision with non-cached file. If you want to over
write, please sync and try again.
16-09-27 19:19:05.963 [WARNING] [acd_cli] - Return value error code: 256.

Attempt 3 failed. BackendException: Error running 'acd_cli upload --force --overwrite '/tmp/duplicity-01ebyH-tempdir/duplicity-full.20160927T164650Z.vol11.difftar.gpg' 
'/duplicity/files'': returned 1, with output:
[#########################] 100.0% of  100MiB  1/1    3.6MB/s       0s
1 file(s) failed.

16-09-27 19:21:48.393 [ERROR] [acd_cli] - Uploading "duplicity-full.20160927T164650Z.vol11.difftar.gpg" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
16-09-27 19:21:48.450 [WARNING] [acd_cli] - Return value error code: 256.

Attempt 4 failed. BackendException: Error running 'acd_cli upload --force --overwrite '/tmp/duplicity-01ebyH-tempdir/duplicity-full.20160927T164650Z.vol11.difftar.gpg' '/duplicity/files'': returned 1, with output:
[#########################] 100.0% of  100MiB  1/1    1.0MB/s       0s
1 file(s) failed.

16-09-27 19:25:11.198 [ERROR] [acd_cli] - Uploading "duplicity-full.20160927T164650Z.vol11.difftar.gpg" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
16-09-27 19:25:11.233 [WARNING] [acd_cli] - Return value error code: 256.

Giving up after 5 attempts. BackendException: Error running 'acd_cli upload --force --overwrite '/tmp/duplicity-01ebyH-tempdir/duplicity-full.20160927T164650Z.vol11.difftar.gpg' '/duplicity/files'': returned 1, with output:
[#########################] 100.0% of  100MiB  1/1    4.0MB/s       0s
1 file(s) failed.

16-09-27 19:26:14.138 [ERROR] [acd_cli] - Uploading "duplicity-full.20160927T164650Z.vol11.difftar.gpg" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
16-09-27 19:26:14.273 [WARNING] [acd_cli] - Return value error code: 256.

```

**Comment by breunigs** [comment]
Update acd_cli. Recent versions automatically wait for read timeouts so this error would not be pushed into duplicity in the first place.

On top of that the duplicity acdcli backend is out of service as far as I am concerned. I have a replacement that directly talks to Amazon's API. I have requested production limits for the keys for duplicity, but by now I guess they will never arrive. It took them a month to tell me that I was placed in the review queue, so, yeah, not exactly like Prime ¯\_(ツ)_/¯

**Comment by twinther** [comment]
Well I'm already on the latest version, it's same code as git master.
I solved it by adding this simple method
```
def _retry_cleanup(self):
    self.subprocess_popen(self.acd_cmd + " sync")
```

**Comment by breunigs** [comment]
Instead of hacking the variant that relies on acd_cli, would you consider testing the [direct branch in this repository](https://github.com/breunigs/duplicity-acdcli/tree/direct)? It directly talks to AmazonDrive, which should make things simpler. Since the filename and prefix is different, you'd only need to copy the file as described in the [README](https://github.com/breunigs/duplicity-acdcli/blob/direct/README.md) and change the backup target from `acd+acdcli://bla` to `amazondrive://bla`.

**Comment by twinther** [comment]
Sure, it's currently running a large backup set and appears to be working just fine.
I've only seen one timeout at this point but it recovered from that without any problems.
Output was:
Attempt 1 failed. ConnectionError: ('The write operation timed out',)

**Comment by twinther** [comment]
Some feedback on the direct branch, let me know if you want new/separate issues:

1)
I saw this backtrace at one point
```
. Backtrace of previous error: Traceback (innermost last):
.   File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 369, in inner_retry
.     return fn(self, *args)
.   File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 522, in put
.     self.__do_put(source_path, remote_filename)
.   File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 508, in __do_put
.     self.backend._put(source_path, remote_filename)
.   File "/usr/lib/python2.7/dist-packages/duplicity/backends/amazondrivebackend.py", line 267, in _put
.     quota.raise_for_status()
.   File "/usr/lib/python2.7/dist-packages/requests/models.py", line 837, in raise_for_status
.     raise HTTPError(http_error_msg, response=self)
.  HTTPError: 500 Server Error: Internal Server Error for url: https://cdws.us-east-1.amazonaws.com/drive/v1/account/quota
```
Unfortunately I lost the output from duplicity but the was a python key error ['id'] or similar afterwards. I'll keep an eye out for that.


2)
I run duplicity with cron and this behaviour is a problem for me because the backup is aborted.
```
RESTART: Volumes 14 to 15 failed to upload before termination.
         Restarting backup at volume 14.
Restarting after volume 13, file GoPro/2013 Test/GOPR0011.LRV, block 9
Amazon reports that duplicity-full.20161006T064050Z.vol14.difftar.gpg already exits. Local size: 104911927. Remote size: 104911890.
```
I don't know what the solution could be. I guess the problem with different file sizes is due to GPG encryption, because I'm quite sure the files being backed up has changed.

Br.
Tommy

**Comment by breunigs** [comment]
1) seems to be duplicity already fails on checking the remaining available space. I had never happen that before, but duplicity should retry failed uploads by itself anyway, so that should be okay.

I have seen the `['id']` error though and have a local patch I forgot to commit. I have pushed the fix now, can you update again?

2) I have seen this error, too, but I am not quite sure where it comes from yet. It seems that although the upload of volume 14 was finished previously, duplicity wants to override it. I will have to check if this is intended and then just change to code to override the file.

**Comment by breunigs** [comment]
Yep, turns out the correct behaviour is to overwrite files if they already exist. I have a patch I will test tonight and push it tomorrow, if my backups appear to work fine.

**Comment by twinther** [comment]
I tried the new version and it looks pretty good.

```
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: none
Last full backup is too old, forcing full backup
Attempt 1 failed. ConnectionError: ('The write operation timed out',)
Attempt 1 failed. ConnectionError: ('The write operation timed out',)
Attempt 1 failed. ConnectionError: ('The write operation timed out',)
Attempt 1 failed. ConnectionError: ('The write operation timed out',)
Attempt 1 failed. ConnectionError: ('The write operation timed out',)
Attempt 1 failed. ConnectionError: ('The write operation timed out',)
Attempt 1 failed. ConnectionError: ('The write operation timed out',)
Attempt 1 failed. ConnectionError: ('The write operation timed out',)
Attempt 1 failed. ConnectionError: ('The write operation timed out',)
Attempt 1 failed. ConnectionError: ('The write operation timed out',)
Attempt 1 failed. ConnectionError: ('The write operation timed out',)
Attempt 1 failed. ConnectionError: ('The write operation timed out',)
Attempt 1 failed. ConnectionError: ('The read operation timed out',)
Upload failed, because there was a file with the same name as duplicity-full.20161010T065322Z.vol47.difftar.gpg already present. The file was deleted, and duplicity will retry the upload unless the retry limit has been reached.
```

It recovered from a lot of time outs, but it looks like it aborted after the "Upload failed" line.
The file duplicity-full.20161010T065322Z.vol47.difftar.gpg was deleted on the amazon cloud drive.
Running duplicity again I get:
```
Local and Remote metadata are synchronized, no sync needed.
Last full backup left a partial set, restarting.
Last full backup date: Mon Oct 10 08:53:22 2016
RESTART: Volumes 46 to 47 failed to upload before termination.
         Restarting backup at volume 46.
Restarting after volume 45, file SNIP, block 23177
```

**Comment by breunigs** [comment]
Awesome catch! I have pushed a new commit to fix this. The cause was a simple blunder on my part: `log.FatalError` directly exits instead of retrying, like `raise BackendException`. So yeah, it now should retry after that error message instead of just silently quitting. 

I wonder though how you get so many timeouts. If you have ~50 volumes and ~10 retries in those, that'd mean a lot of bandwidth wasted. Did you disconnect the internet in between? What volsize do you use? I know that Amazon sometimes can't cope and will return a status code 504 or 408 for timeouts, but those errors are much more low level from Python itself, so I am not quite sure how to handle it.

**Comment by twinther** [comment]
I've been running with the last code for a while and it's running great! I did get an occasional KeyError 'data' but duplicity just retried.
I'm using --volsize 100. I also still get a lot of timeouts. I don't think it's my internet, it's usually rock solid, and it's probably not your code either. I'm located in Europe and cloud drive is in the US, so it's probably related to that somehow.

I'm pretty happy with the current version so I'll use that over acd_cli from now on. I'll let you know if anything pops up. Thanks for your awesome work!
Do you plan to include it in duplicity over the acd_cli backend?

**Comment by breunigs** [comment]
Yeah, I guess the volsize might be related, but I only thought it'd be an issue for something like 1GB+. I checked the documentation for Python requests (which handles the connections for me) and it defaults to an unlimited waiting time. So it appears that something closes the connection/socket while Amazon is stalling. I wonder if it is Amazon itself. For instance, rclone rechecks after any of these error codes for some minutes to see if the upload completed.
```
//  * 408 REQUEST_TIMEOUT
//  * 504 GATEWAY_TIMEOUT
//  * 500 Internal server error
```
I will push a version with more debug logging later. Would you run the backup in with debug logging at and copy the log of at least one the "timeout areas". I don't need the list of included files obviously, so you can just skip that part.

And yes, I plan to send the patch upstream. I just announced the backend to today on the mailing list, to beta test it with a bigger audience. I guess it will be in addition to the acd_cli one though, because it needs user interaction for the new oauth.

**Comment by breunigs** [comment]
Here's a very experimental version: http://sprunge.us/eceW It essentially catches all kinds of errors during upload and just staggers on. It tries to read the status code, even though I am not even sure if it's there. It also doesn't do anything about it, like sleeping+waiting and see if Amazon manages by itself in the end. So, this version is definitely just a first step to see if the timeout issues you experience are related to that. Can you please test and report back?

**Comment by breunigs** [comment]
Hm, I just realized. Can you try to pass `--timeout 120` to duplicity and see if that helps?

**Comment by twinther** [comment]
Thanks for your work on this :)

I tried with --timeout 120 but that didn't change anything.
It's currently running with the experimental version. There is small problem in line 316 where the parameter for replacement string %d seconds is not passed. I changed it to this locally since it's just a log statement:
`316                      'type=%s args=%s' % (remote_filename, self.WAIT_ON_UPLOAD_ERROR_SECONDS, type(err), err))  
`

So far I've seen this logged twice and otherwise no errors or retries, but I'll let it run for a while:

```
Attempt 1 failed. BackendException: duplicity-full.20161017T071240Z.vol143.difftar.gpg upload failed and file did not show up within time limit.
Attempt 1 failed. BackendException: duplicity-full.20161017T071240Z.vol144.difftar.gpg upload failed and file did not show up within time limit.

```

**Comment by twinther** [comment]
A backtrace:

```
INFO 1
. duplicity-full.20161017T071240Z.vol580.difftar.gpg upload failed. Speculatively waiting for 480 seconds to see if AmazonDrive finished the upload correctly, but close
d the connection before returning the result. type=<class 'requests.exceptions.ConnectionError'> args=('The write operation timed out',)

DEBUG 1
. Uploaded file is not yet there, 48 tries left.
[snip]
DEBUG 1
. Uploaded file is not yet there, 28 tries left.

DEBUG 1
. Backtrace of previous error: Traceback (innermost last):
.   File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 369, in inner_retry
.     return fn(self, *args)
.   File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 522, in put
.     self.__do_put(source_path, remote_filename)
.   File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 508, in __do_put
.     self.backend._put(source_path, remote_filename)
.   File "/usr/lib/python2.7/dist-packages/duplicity/backends/amazondrivebackend.py", line 322, in _put
.     remote_size = self._query(remote_filename)['size']
.   File "/usr/lib/python2.7/dist-packages/duplicity/backends/amazondrivebackend.py", line 376, in _query
.     file_id = self.get_file_id(remote_filename)
.   File "/usr/lib/python2.7/dist-packages/duplicity/backends/amazondrivebackend.py", line 208, in get_file_id
.     self._list()
.   File "/usr/lib/python2.7/dist-packages/duplicity/backends/amazondrivebackend.py", line 389, in _list
.     '/children?filters=kind:FILE')
.   File "/usr/lib/python2.7/dist-packages/duplicity/backends/amazondrivebackend.py", line 256, in read_all_pages
.     result.extend(json_response['data'])
.  KeyError: 'data'
. 
```

Another one:

```
INFO 1
. duplicity-full.20161017T071240Z.vol616.difftar.gpg upload failed. Speculatively waiting for 480 seconds to see if AmazonDrive finished the upload correctly, but close
d the connection before returning the result. type=<class 'requests.exceptions.ConnectionError'> args=('The write operation timed out',)

DEBUG 1
. Uploaded file is not yet there, 48 tries left.
[snip]
DEBUG 1
. Uploaded file is not yet there, 0 tries left.

DEBUG 1
. Backtrace of previous error: Traceback (innermost last):
.   File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 369, in inner_retry
.     return fn(self, *args)
.   File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 522, in put
.     self.__do_put(source_path, remote_filename)
.   File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 508, in __do_put
.     self.backend._put(source_path, remote_filename)
.   File "/usr/lib/python2.7/dist-packages/duplicity/backends/amazondrivebackend.py", line 333, in _put
.     'within time limit.' % remote_filename)
.  BackendException: duplicity-full.20161017T071240Z.vol616.difftar.gpg upload failed and file did not show up within time limit.
. 

WARNING 1
. Attempt 1 failed. BackendException: duplicity-full.20161017T071240Z.vol616.difftar.gpg upload failed and file did not show up within time limit.

INFO 1
. Writing duplicity-full.20161017T071240Z.vol616.difftar.gpg

DEBUG 1
. duplicity-full.20161017T071240Z.vol616.difftar.gpg uploaded successfully

```

**Comment by breunigs** [comment]
The backtraces indicate something goes wrong when it tries to enumerate all files in the backup folder. I have pushed some changes that make this `read_all_pages` more verbose and also more robust regarding to the output.

The "wait and see if file appears" feature you already tested is also there. It doesn't help in your case though, since the connection gets closed for whatever reason before the upload is actually finished. This makes it actually worse for you, since waiting in these cases doesn't make any sense -- the file will not appear anyway. I'll think a bit more about this, but I guess this feature needs to be only invoked when AmazonDrive responds with 408 or 504.
